
!whitespace
: ' '
| '\t'
| '\r'
| '\n'
;

// --- [ Identifiers ] 
identifier 	
: _letter { _letter | _decimalDigit } 
;

// --- [ Letters and digits ]

_letter       	
: _unicodeLetter 
| '_' 
| '-'
;

_unicodeLetter 	
: 'a' - 'z' 
| 'A' - 'Z' 
;

_decimalDigit  	
: '0' - '9' 
;

_octalDigit
: '0' - '7' 
;

_hexDigit      	
: _decimalDigit 
| 'a' - 'f' 
| 'A' - 'F' 
;

tagNN
: '<' 'N' 'N' '>'
;

tagNNP
: '<' 'N' 'N' 'P' '>'
;

tagVBZ
: '<' 'V' 'B' 'Z' '>'
;

tagDT
: '<' 'D' 'T' '>'
;

tagPeroid
: '<' '.' '>'
;

// === [ Grammer part] 

<< import "github.com/english-lang/english/ast/internal" >>


DeclarativeSentence
: NNPWord VBZWord DTWord NNWord PeroidWord
;

NNWord
: Word tagNN << internal.NewWord($0,$1), nil >>
;

NNPWord
: Word tagNNP << internal.NewWord($0,$1), nil >>
;

DTWord
: Word tagDT << internal.NewWord($0,$1), nil >>
;

VBZWord
: Word tagVBZ << internal.NewWord($0,$1), nil >>
;

PeroidWord
: "." tagPeroid << internal.NewWord($0,$1), nil >>
;

Word
: identifier
;
