// Code generated by gocc; DO NOT EDIT.

package lexer

/*
Let s be the current state
Let r be the current input rune
transitionTable[s](r) returns the next state.
*/
type TransitionTable [NumStates]func(rune) int

var TransTab = TransitionTable{
	// S0
	func(r rune) int {
		switch {
		case r == 9: // ['\t','\t']
			return 1
		case r == 10: // ['\n','\n']
			return 1
		case r == 13: // ['\r','\r']
			return 1
		case r == 32: // [' ',' ']
			return 1
		case r == 45: // ['-','-']
			return 2
		case r == 46: // ['.','.']
			return 3
		case r == 60: // ['<','<']
			return 4
		case 65 <= r && r <= 90: // ['A','Z']
			return 5
		case r == 95: // ['_','_']
			return 2
		case 97 <= r && r <= 122: // ['a','z']
			return 5
		}
		return NoState
	},
	// S1
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S2
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 2
		case 48 <= r && r <= 57: // ['0','9']
			return 6
		case 65 <= r && r <= 90: // ['A','Z']
			return 5
		case r == 95: // ['_','_']
			return 2
		case 97 <= r && r <= 122: // ['a','z']
			return 5
		}
		return NoState
	},
	// S3
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S4
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 7
		case r == 68: // ['D','D']
			return 8
		case r == 78: // ['N','N']
			return 9
		case r == 86: // ['V','V']
			return 10
		}
		return NoState
	},
	// S5
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 2
		case 48 <= r && r <= 57: // ['0','9']
			return 6
		case 65 <= r && r <= 90: // ['A','Z']
			return 5
		case r == 95: // ['_','_']
			return 2
		case 97 <= r && r <= 122: // ['a','z']
			return 5
		}
		return NoState
	},
	// S6
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 2
		case 48 <= r && r <= 57: // ['0','9']
			return 6
		case 65 <= r && r <= 90: // ['A','Z']
			return 5
		case r == 95: // ['_','_']
			return 2
		case 97 <= r && r <= 122: // ['a','z']
			return 5
		}
		return NoState
	},
	// S7
	func(r rune) int {
		switch {
		case r == 62: // ['>','>']
			return 11
		}
		return NoState
	},
	// S8
	func(r rune) int {
		switch {
		case r == 84: // ['T','T']
			return 12
		}
		return NoState
	},
	// S9
	func(r rune) int {
		switch {
		case r == 78: // ['N','N']
			return 13
		}
		return NoState
	},
	// S10
	func(r rune) int {
		switch {
		case r == 66: // ['B','B']
			return 14
		}
		return NoState
	},
	// S11
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S12
	func(r rune) int {
		switch {
		case r == 62: // ['>','>']
			return 15
		}
		return NoState
	},
	// S13
	func(r rune) int {
		switch {
		case r == 62: // ['>','>']
			return 16
		case r == 80: // ['P','P']
			return 17
		}
		return NoState
	},
	// S14
	func(r rune) int {
		switch {
		case r == 90: // ['Z','Z']
			return 18
		}
		return NoState
	},
	// S15
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S16
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S17
	func(r rune) int {
		switch {
		case r == 62: // ['>','>']
			return 19
		}
		return NoState
	},
	// S18
	func(r rune) int {
		switch {
		case r == 62: // ['>','>']
			return 20
		}
		return NoState
	},
	// S19
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S20
	func(r rune) int {
		switch {
		}
		return NoState
	},
}
