// Code generated by gocc; DO NOT EDIT.

package parser

type (
	actionTable [numStates]actionRow
	actionRow   struct {
		canRecover bool
		actions    [numSymbols]action
	}
)

var actionTab = actionTable{
	actionRow{ // S0
		canRecover: false,
		actions: [numSymbols]action{
			nil,      /* INVALID */
			nil,      /* $ */
			nil,      /* tagNN */
			nil,      /* tagNNP */
			nil,      /* tagDT */
			nil,      /* tagVBZ */
			nil,      /* . */
			nil,      /* tagPeroid */
			shift(4), /* identifier */
		},
	},
	actionRow{ // S1
		canRecover: false,
		actions: [numSymbols]action{
			nil,          /* INVALID */
			accept(true), /* $ */
			nil,          /* tagNN */
			nil,          /* tagNNP */
			nil,          /* tagDT */
			nil,          /* tagVBZ */
			nil,          /* . */
			nil,          /* tagPeroid */
			nil,          /* identifier */
		},
	},
	actionRow{ // S2
		canRecover: false,
		actions: [numSymbols]action{
			nil,      /* INVALID */
			nil,      /* $ */
			nil,      /* tagNN */
			nil,      /* tagNNP */
			nil,      /* tagDT */
			nil,      /* tagVBZ */
			nil,      /* . */
			nil,      /* tagPeroid */
			shift(7), /* identifier */
		},
	},
	actionRow{ // S3
		canRecover: false,
		actions: [numSymbols]action{
			nil,      /* INVALID */
			nil,      /* $ */
			nil,      /* tagNN */
			shift(8), /* tagNNP */
			nil,      /* tagDT */
			nil,      /* tagVBZ */
			nil,      /* . */
			nil,      /* tagPeroid */
			nil,      /* identifier */
		},
	},
	actionRow{ // S4
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* tagNN */
			reduce(7), /* tagNNP, reduce: Word */
			nil,       /* tagDT */
			nil,       /* tagVBZ */
			nil,       /* . */
			nil,       /* tagPeroid */
			nil,       /* identifier */
		},
	},
	actionRow{ // S5
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* tagNN */
			nil,       /* tagNNP */
			nil,       /* tagDT */
			nil,       /* tagVBZ */
			nil,       /* . */
			nil,       /* tagPeroid */
			shift(11), /* identifier */
		},
	},
	actionRow{ // S6
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* tagNN */
			nil,       /* tagNNP */
			nil,       /* tagDT */
			shift(12), /* tagVBZ */
			nil,       /* . */
			nil,       /* tagPeroid */
			nil,       /* identifier */
		},
	},
	actionRow{ // S7
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* tagNN */
			nil,       /* tagNNP */
			nil,       /* tagDT */
			reduce(7), /* tagVBZ, reduce: Word */
			nil,       /* . */
			nil,       /* tagPeroid */
			nil,       /* identifier */
		},
	},
	actionRow{ // S8
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* tagNN */
			nil,       /* tagNNP */
			nil,       /* tagDT */
			nil,       /* tagVBZ */
			nil,       /* . */
			nil,       /* tagPeroid */
			reduce(3), /* identifier, reduce: NNPWord */
		},
	},
	actionRow{ // S9
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* tagNN */
			nil,       /* tagNNP */
			nil,       /* tagDT */
			nil,       /* tagVBZ */
			nil,       /* . */
			nil,       /* tagPeroid */
			shift(15), /* identifier */
		},
	},
	actionRow{ // S10
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* tagNN */
			nil,       /* tagNNP */
			shift(16), /* tagDT */
			nil,       /* tagVBZ */
			nil,       /* . */
			nil,       /* tagPeroid */
			nil,       /* identifier */
		},
	},
	actionRow{ // S11
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* tagNN */
			nil,       /* tagNNP */
			reduce(7), /* tagDT, reduce: Word */
			nil,       /* tagVBZ */
			nil,       /* . */
			nil,       /* tagPeroid */
			nil,       /* identifier */
		},
	},
	actionRow{ // S12
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* tagNN */
			nil,       /* tagNNP */
			nil,       /* tagDT */
			nil,       /* tagVBZ */
			nil,       /* . */
			nil,       /* tagPeroid */
			reduce(5), /* identifier, reduce: VBZWord */
		},
	},
	actionRow{ // S13
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* tagNN */
			nil,       /* tagNNP */
			nil,       /* tagDT */
			nil,       /* tagVBZ */
			shift(18), /* . */
			nil,       /* tagPeroid */
			nil,       /* identifier */
		},
	},
	actionRow{ // S14
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			shift(19), /* tagNN */
			nil,       /* tagNNP */
			nil,       /* tagDT */
			nil,       /* tagVBZ */
			nil,       /* . */
			nil,       /* tagPeroid */
			nil,       /* identifier */
		},
	},
	actionRow{ // S15
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			reduce(7), /* tagNN, reduce: Word */
			nil,       /* tagNNP */
			nil,       /* tagDT */
			nil,       /* tagVBZ */
			nil,       /* . */
			nil,       /* tagPeroid */
			nil,       /* identifier */
		},
	},
	actionRow{ // S16
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* tagNN */
			nil,       /* tagNNP */
			nil,       /* tagDT */
			nil,       /* tagVBZ */
			nil,       /* . */
			nil,       /* tagPeroid */
			reduce(4), /* identifier, reduce: DTWord */
		},
	},
	actionRow{ // S17
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			reduce(1), /* $, reduce: DeclarativeSentence */
			nil,       /* tagNN */
			nil,       /* tagNNP */
			nil,       /* tagDT */
			nil,       /* tagVBZ */
			nil,       /* . */
			nil,       /* tagPeroid */
			nil,       /* identifier */
		},
	},
	actionRow{ // S18
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* tagNN */
			nil,       /* tagNNP */
			nil,       /* tagDT */
			nil,       /* tagVBZ */
			nil,       /* . */
			shift(20), /* tagPeroid */
			nil,       /* identifier */
		},
	},
	actionRow{ // S19
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* tagNN */
			nil,       /* tagNNP */
			nil,       /* tagDT */
			nil,       /* tagVBZ */
			reduce(2), /* ., reduce: NNWord */
			nil,       /* tagPeroid */
			nil,       /* identifier */
		},
	},
	actionRow{ // S20
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			reduce(6), /* $, reduce: PeroidWord */
			nil,       /* tagNN */
			nil,       /* tagNNP */
			nil,       /* tagDT */
			nil,       /* tagVBZ */
			nil,       /* . */
			nil,       /* tagPeroid */
			nil,       /* identifier */
		},
	},
}
