// Code generated by gocc; DO NOT EDIT.

package parser

const numNTSymbols = 8

type (
	gotoTable [numStates]gotoRow
	gotoRow   [numNTSymbols]int
)

var gotoTab = gotoTable{
	gotoRow{ // S0
		-1, // S'
		1,  // DeclarativeSentence
		-1, // NNWord
		2,  // NNPWord
		-1, // DTWord
		-1, // VBZWord
		-1, // PeriodWord
		3,  // Word
	},
	gotoRow{ // S1
		-1, // S'
		-1, // DeclarativeSentence
		-1, // NNWord
		-1, // NNPWord
		-1, // DTWord
		-1, // VBZWord
		-1, // PeriodWord
		-1, // Word
	},
	gotoRow{ // S2
		-1, // S'
		-1, // DeclarativeSentence
		-1, // NNWord
		-1, // NNPWord
		-1, // DTWord
		5,  // VBZWord
		-1, // PeriodWord
		6,  // Word
	},
	gotoRow{ // S3
		-1, // S'
		-1, // DeclarativeSentence
		-1, // NNWord
		-1, // NNPWord
		-1, // DTWord
		-1, // VBZWord
		-1, // PeriodWord
		-1, // Word
	},
	gotoRow{ // S4
		-1, // S'
		-1, // DeclarativeSentence
		-1, // NNWord
		-1, // NNPWord
		-1, // DTWord
		-1, // VBZWord
		-1, // PeriodWord
		-1, // Word
	},
	gotoRow{ // S5
		-1, // S'
		-1, // DeclarativeSentence
		-1, // NNWord
		-1, // NNPWord
		9,  // DTWord
		-1, // VBZWord
		-1, // PeriodWord
		10, // Word
	},
	gotoRow{ // S6
		-1, // S'
		-1, // DeclarativeSentence
		-1, // NNWord
		-1, // NNPWord
		-1, // DTWord
		-1, // VBZWord
		-1, // PeriodWord
		-1, // Word
	},
	gotoRow{ // S7
		-1, // S'
		-1, // DeclarativeSentence
		-1, // NNWord
		-1, // NNPWord
		-1, // DTWord
		-1, // VBZWord
		-1, // PeriodWord
		-1, // Word
	},
	gotoRow{ // S8
		-1, // S'
		-1, // DeclarativeSentence
		-1, // NNWord
		-1, // NNPWord
		-1, // DTWord
		-1, // VBZWord
		-1, // PeriodWord
		-1, // Word
	},
	gotoRow{ // S9
		-1, // S'
		-1, // DeclarativeSentence
		13, // NNWord
		-1, // NNPWord
		-1, // DTWord
		-1, // VBZWord
		-1, // PeriodWord
		14, // Word
	},
	gotoRow{ // S10
		-1, // S'
		-1, // DeclarativeSentence
		-1, // NNWord
		-1, // NNPWord
		-1, // DTWord
		-1, // VBZWord
		-1, // PeriodWord
		-1, // Word
	},
	gotoRow{ // S11
		-1, // S'
		-1, // DeclarativeSentence
		-1, // NNWord
		-1, // NNPWord
		-1, // DTWord
		-1, // VBZWord
		-1, // PeriodWord
		-1, // Word
	},
	gotoRow{ // S12
		-1, // S'
		-1, // DeclarativeSentence
		-1, // NNWord
		-1, // NNPWord
		-1, // DTWord
		-1, // VBZWord
		-1, // PeriodWord
		-1, // Word
	},
	gotoRow{ // S13
		-1, // S'
		-1, // DeclarativeSentence
		-1, // NNWord
		-1, // NNPWord
		-1, // DTWord
		-1, // VBZWord
		17, // PeriodWord
		-1, // Word
	},
	gotoRow{ // S14
		-1, // S'
		-1, // DeclarativeSentence
		-1, // NNWord
		-1, // NNPWord
		-1, // DTWord
		-1, // VBZWord
		-1, // PeriodWord
		-1, // Word
	},
	gotoRow{ // S15
		-1, // S'
		-1, // DeclarativeSentence
		-1, // NNWord
		-1, // NNPWord
		-1, // DTWord
		-1, // VBZWord
		-1, // PeriodWord
		-1, // Word
	},
	gotoRow{ // S16
		-1, // S'
		-1, // DeclarativeSentence
		-1, // NNWord
		-1, // NNPWord
		-1, // DTWord
		-1, // VBZWord
		-1, // PeriodWord
		-1, // Word
	},
	gotoRow{ // S17
		-1, // S'
		-1, // DeclarativeSentence
		-1, // NNWord
		-1, // NNPWord
		-1, // DTWord
		-1, // VBZWord
		-1, // PeriodWord
		-1, // Word
	},
	gotoRow{ // S18
		-1, // S'
		-1, // DeclarativeSentence
		-1, // NNWord
		-1, // NNPWord
		-1, // DTWord
		-1, // VBZWord
		-1, // PeriodWord
		-1, // Word
	},
	gotoRow{ // S19
		-1, // S'
		-1, // DeclarativeSentence
		-1, // NNWord
		-1, // NNPWord
		-1, // DTWord
		-1, // VBZWord
		-1, // PeriodWord
		-1, // Word
	},
	gotoRow{ // S20
		-1, // S'
		-1, // DeclarativeSentence
		-1, // NNWord
		-1, // NNPWord
		-1, // DTWord
		-1, // VBZWord
		-1, // PeriodWord
		-1, // Word
	},
}
