// Code generated by gocc; DO NOT EDIT.

package parser

import "github.com/english-lang/english/ast/internal"

type (
	//TODO: change type and variable names to be consistent with other tables
	ProdTab      [numProductions]ProdTabEntry
	ProdTabEntry struct {
		String     string
		Id         string
		NTType     int
		Index      int
		NumSymbols int
		ReduceFunc func([]Attrib) (Attrib, error)
	}
	Attrib interface {
	}
)

var productionsTable = ProdTab{
	ProdTabEntry{
		String: `S' : DeclarativeSentence	<<  >>`,
		Id:         "S'",
		NTType:     0,
		Index:      0,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `DeclarativeSentence : NNPWord VBZWord DTWord NNWord PeriodWord	<< internal.NewSentence("DeclarativeSentence",X[0],X[1],X[2],X[3],X[4]), nil >>`,
		Id:         "DeclarativeSentence",
		NTType:     1,
		Index:      1,
		NumSymbols: 5,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return internal.NewSentence("DeclarativeSentence",X[0],X[1],X[2],X[3],X[4]), nil
		},
	},
	ProdTabEntry{
		String: `NNWord : Word tagNN	<< internal.NewWord(X[0],"NN"), nil >>`,
		Id:         "NNWord",
		NTType:     2,
		Index:      2,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return internal.NewWord(X[0],"NN"), nil
		},
	},
	ProdTabEntry{
		String: `NNPWord : Word tagNNP	<< internal.NewWord(X[0],"NNP"), nil >>`,
		Id:         "NNPWord",
		NTType:     3,
		Index:      3,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return internal.NewWord(X[0],"NNP"), nil
		},
	},
	ProdTabEntry{
		String: `DTWord : Word tagDT	<< internal.NewWord(X[0],"DT"), nil >>`,
		Id:         "DTWord",
		NTType:     4,
		Index:      4,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return internal.NewWord(X[0],"DT"), nil
		},
	},
	ProdTabEntry{
		String: `VBZWord : Word tagVBZ	<< internal.NewWord(X[0],"VBZ"), nil >>`,
		Id:         "VBZWord",
		NTType:     5,
		Index:      5,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return internal.NewWord(X[0],"VBZ"), nil
		},
	},
	ProdTabEntry{
		String: `PeriodWord : "." tagPeriod	<< internal.NewWord(X[0],"."), nil >>`,
		Id:         "PeriodWord",
		NTType:     6,
		Index:      6,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return internal.NewWord(X[0],"."), nil
		},
	},
	ProdTabEntry{
		String: `Word : identifier	<<  >>`,
		Id:         "Word",
		NTType:     7,
		Index:      7,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
}
